on: [push, pull_request]

name: CI

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings


  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.58.0  # MSRV
        platform:
          - aarch64-unknown-linux-gnu
          - aarch64-linux-android
          - aarch64-apple-ios
          - arm-unknown-linux-gnueabi
          - arm-linux-androideabi
          - armv7-unknown-linux-gnueabihf
          - armv7-linux-androideabi
          - armv7-apple-ios
          - armv7s-apple-ios
          - i686-unknown-linux-gnu
          - i686-unknown-linux-musl
          - i686-unknown-freebsd
          - i686-apple-ios
          - i686-apple-darwin
          - i686-linux-android
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - x86_64-linux-android
          - x86_64-apple-darwin
          - x86_64-apple-ios
          - x86_64-unknown-freebsd
          - wasm32-unknown-emscripten
          - wasm32-unknown-unknown

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.platform }}
          override: true

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target ${{ matrix.platform }}